services:
  next-app:
    container_name: connex-app
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - strapi_cms

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  strapi_cms:
    name: connex
    external: true